config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Redirects /orders/pending to /orders?pending=true.
  get '/orders/pending', to: redirect('orders?pending=true')

  resources :orders do
    get 'recent', on: :collection
    put 'ship', on: :member
  end
  
  resources :line_items do
    #put 'decrement', on: :member 
    put 'decrement', on: :member
  end
  resources :carts
  get 'store/index'

  resources :products do
    get :who_bought, on: :member
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'store#index', as: 'store'
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items, dependent: :destroy
  PAYMENT_TYPES = [ "Check", "Credit Card", "Purchase Order" ]
  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
  # copied from cart since we print total in email
  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:new, :create]
  before_action :set_order, only: [:show, :edit, :update, :destroy, :ship]

  # GET /orders
  # GET /orders.json
  def index
    pending = params[:pending] || false
    if pending
      @title = "Pending Orders"
      @orders = Order.where("status IS NULL")
    else
      @orders = Order.all
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  # checkout comes here
  def new
    if @cart.line_items.empty?
      redirect_to store_url, notice: 'Your cart is empty'
      return
    end
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  # place order comes here
  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(@cart)

    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        OrderNotifierMailer.received(@order).deliver_later
        #format.html { redirect_to store_url, notice: 'Thank you for your order.' }
        format.html { redirect_to store_url, notice: %Q[Thank you for your #{view_context.link_to('order', @order)}.] }
        #flash[:notice] = "Successfully created #{view_context.link_to('product', @product)}."
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def recent
    @orders = Order.order(id: :desc).last(20)
  end
  def ship
    @order.status = "shipped"
    @order.save!
    respond_to do |format|
      format.html { redirect_to order_path, notice: 'Order was successfully shipped.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :address, :email, :pay_type)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, size: 40 %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_area :address, rows: 3, cols: 40 %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, size: 40 %>
  </div>

  <div class="field">
    <%= f.label :pay_type %><br>
    <%= f.select :pay_type, Order::PAYMENT_TYPES,
    prompt: "Select a payment method" %>
  </div>

  <div class="actions">
    <%= f.submit "Place Order" %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>
<% title = @title || "Orders" %>
<h1><%= title %></h1>

<div class="container">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Address</th>
      <th>Email</th>
      <th>Pay type</th>
      <th>Value</th>
      <th>Items</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.name %></td>
        <td><%= order.address %></td>
        <td><%= order.email %></td>
        <td><%= order.pay_type %></td>
        <td><%= order.total_price %></td>
        <td><%= order.line_items.count %></td>
        <td><%= link_to '', order , class: 'glyphicon glyphicon-folder-open' %></td>
        <td><%= link_to '', edit_order_path(order), class: 'glyphicon glyphicon-edit' %></td>
        <td><%= link_to '', order, method: :delete, data: { confirm: 'Are you sure?' }, class: 'glyphicon glyphicon-remove' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<div class="depot_form">
  <fieldset>
    <legend>Please enter your details</legend>
    <%= render 'form', order: @order %>
  </fieldset>
</div>

<%= link_to 'Back', orders_path %>

app/views/orders/recent.html.erb
<p id="notice"><%= notice %></p>

<h1>Recent Orders</h1>

<div class="container">
<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Address</th>
      <th>Email</th>
      <th>Pay type</th>
      <th>Value</th>
      <th>Items</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <% if order.status == 'shipped' %>
      <tr class="success">
      <% else %>
      <tr class="warning">
      <% end %>

        <td><%= order.id %></td>
        <td><%= order.name %></td>
        <td><%= order.address %></td>
        <td><%= order.email %></td>
        <td><%= order.pay_type %></td>
        <td><%= order.total_price %></td>
        <td><%= order.line_items.count %></td>
        <td><%= order.status %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>


<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  
  <table class="table">
    <tr>
      <td align=right>
        <strong>Id:</strong>
      </td>
      <td>
        <%= @order.id %>
      </td>
    </tr>
    <tr>
      <td align=right>
        <strong>Name:</strong>
      </td>
      <td>
        <%= @order.name %>
      </td>
    </tr>
    
    <tr>
      <td align=right>
        <strong>Address:</strong>
      </td>
      <td>
        <%= @order.address %>
      </td>
    </tr>
    
    <tr>
      <td align=right>
        <strong>Email:</strong>
      </td>
      <td>
        <%= @order.email %>
      </td>
    </tr>
    
    <tr>
      <td align=right>
        <strong>Pay type:</strong>
      </td>
      <td>
        <%= @order.pay_type %>
      </td>
    </tr>
    <tr>
      <td align=right>
        <strong>Status:</strong>
      </td>
      <td>
        <%= @order.status || "pending" %>
      </td>
    </tr>
  </table>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Qty</th>
        <th>Item</th>
        <th>Price</th>
      </tr>
    </thead>
    <%= render @order.line_items, buttons: false %>
    <tr class="total_line">
      <td colspan="2">Total</td>
      <td class="total_cell"><%= number_to_currency(@order.total_price) %></td>
    </tr>
  </table>
  
  <% if @order.status != 'shipped' %>
  <%= button_to 'Ship', ship_order_path(@order) , method: :put , class: 'btn btn-primary btn-block' %> 
  <% end %>
  
</div>
<div class="container">
  <%= link_to 'Edit', edit_order_path(@order) %> |
  <%= link_to 'Orders', orders_path %>
</div>