config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Redirects /orders/pending to /orders?pending=true.
  get '/orders/pending', to: redirect('orders?pending=true')

  resources :orders do
    get 'recent', on: :collection
    put 'ship', on: :member
  end
  
  resources :line_items do
    #put 'decrement', on: :member 
    put 'decrement', on: :member
  end
  resources :carts
  get 'store/index'

  resources :products do
    get :who_bought, on: :member
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'store#index', as: 'store'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Shop Around the Corner Online Store</title>
  <%= stylesheet_link_tag    "application", media: "all",
    "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
  <div id="banner">
    <%= image_tag("logo.png") %>
    <span class="title"><%= @page_title || "The Shop Around the Corner" %></span>
  </div>
  <div id="columns">
    <div id="side">
      <% if @cart %>
      <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
        <%= render @cart %>
      <% end %>
    <% end %>
      <ul>
        <li> <%= link_to 'Home', store_path %> </li>

        <li><a href="">Questions</a></li>
        <li><a href="">News</a></li>
        <li><a href="">Contact</a></li>
        <li> <%= link_to 'Orders', orders_path %> </li>
        <li> <%= link_to 'Recent', recent_orders_path %> </li>
        <li> <%= link_to 'Pending', orders_pending_path %> </li>

        <% if !user_signed_in? %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li> <%= link_to 'Register', new_user_registration_path %></li>
        <% else %>
          <li>
            User: 
            <%= link_to "#{current_user.name}", current_user %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              Log Out
            <% end %>
          </li>

        <% end %>

      </ul>
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
</body>
</html>